@startuml
!pragma layout smetana

class User {
  - email
  - username
  - passwordHash
}

class Host {
  - name
  - description
}

class Software {
  - name
  - version
}

class Finding {
  - status : FindingStatus
  - detectedAt
  - updatedAt
  - resolvedAt
}

class Vulnerability {
  - cveId
  - description
  - cvssScore
  - cvssVector
  - severity : Severity
  - cweCategory
}

class Reference {
  - url
  - source
}

enum FindingStatus {
  OPEN
  IN_PROGRESS
  RESOLVED
}

enum Severity {
  NONE
  LOW
  MEDIUM
  HIGH
  CRITICAL
}

' --- Kompositioner  ---
User          "1" *-- "0..*" Host          : owns >
Host          "1" *-- "0..*" Software      : runs >
Software      "1" *-- "0..*" Finding       : has >
Vulnerability "1" *-- "0..*" Reference     : documented by >

' --- Aggregering---
Vulnerability "1" o-- "0..*" Finding        : identified in >

' --- Dependencies  ---
Finding       ..> FindingStatus
Vulnerability ..> Severity
@enduml