@startuml
!pragma layout smetana

Class User{
- username
- password
}

Class Host{
- hostName
- description
}

Class Software{
- softwareName
- version
}

Class Finding{
- status
- detectedAt
- updatedAt
- resovledAt
}

Class Vulnerability{
- vulnerabilityDescription
- cvssScore
- Severity
- cwe_catagory
}

enum FindingStatus {
  OPEN
  IN_PROGRESS
  RESOLVED
}


User    "1" *-- "0..*" Host      : owns >
Host   "1" *-- "0..*" Software   : runs >
Software "1" *-- "0..*" Finding   : affected by >
Vulnerability "1" o-- "0..*" Finding : found in >
Finding ..> FindingStatus


@enduml